name: 'DAppNodeSDK publish package'
description: 'Publish a DAppNode package with its SDK'
author: 'DAppNode Association'
inputs:
  developer_address:
    required: false
    description: 'Ethereum address for the mantainer of this package APM repo'
runs:
  using: 'node12'
  main: 'dist/index.js'
