name: 'DAppNodeSDK publish package'
description: 'Publish a DAppNode package with its SDK'
author: 'DAppNode Association'
inputs:
  dir:
    required: false
    description: 'Change the base directory'
    default: './'
  eth_provider:
    required: false
    description: 'Specify an eth provider: "dappnode" (default), "infura", "localhost:5002"'
    default: remote
  content_provider:
    required: false
    description: 'Specify an ipfs provider: "dappnode" (default), "infura", "http://localhost:8545"'
    default: remote
  timeout:
    required: false
    description: 'Overrides default build timeout: "15h", "20min 15s", "5000". Specs npmjs.com/package/timestring'
    default: 60min
  developer_address:
    required: false
    description: 'Ethereum address for the mantainer of this package APM repo'
  dappnode_team_preset:
    required: false
    description: 'Specific set of options used for internal DAppNode releases. Caution: options may change without notice.'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
